package com.javabrains.portfoliotracker.enums;

public enum SectorEnum {
    COMMUNICATION_SERVICES, CONSUMER_DISCRETIONARY, CONSUMER_STAPLES, ENERGY, FINANCIALS,
    HEALT_CARE, INDUSTRIALS, INFORMATION_TECHNOLOGY, MATERIALS, REAL_ESTATE, UTILITIES
}
